ALTER TABLE files DROP COLUMN IF EXISTS checksum;
ALTER TABLE files DROP COLUMN IF EXISTS is_encrypted;
ALTER TABLE files DROP COLUMN IF EXISTS updated_at;
ALTER TABLE directories DROP COLUMN IF EXISTS updated_at;
ALTER TABLE users DROP COLUMN IF EXISTS updated_at;
